config/routes.rb
Rails.application.routes.draw do
  get "search", to: "search#index"
  devise_for :users

  resources :posts do # /posts/1/comments/2
    resources :comments
  end


  get "up" => "rails/health#show", as: :rails_health_check
  get "home", controller: "home", action: "index", as: "home"
  # get "estudante", to: "estudante#index", as: "estudantes"

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_rich_text :body
end

app/models/post.rb
class Post < ApplicationRecord
  after_initialize :set_default_views, if: :new_record?

  private

  def set_default_views
    self.views ||= 0
  end

  belongs_to :user
  has_many :comments, dependent: :destroy # Estou dizendo que 1 post pode conter varios comentários e se o post for excluido, os comentários também serão.
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy # Um usuario pode ter varios posts e se excluido, os posts também serão
  has_many :comments, dependent: :destroy # Um usuario pode ter varios comentarios e se excluido, os comentarios também serão
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user! # Certificando que apenas usuários autenticados
  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Comentário criado com sucesso"
      redirect_to post_path(@post)

    else
      flash[:alert] = "Comentário não foi criado"
      redirect_to post_path(@post)
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  def update
    @comment = @post.comments.find(params[:id]) # Aqui localizo o comentário que quero atualizar
    respond_to do |format|
      if @comment.update(comment_params)
          format.html { redirect_to post_url(@post), notice: "Comentário atualizado" }
      else
        format.html { redirect_to post_url(@post), alert: "Erro na atualização" }
      end
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id]) #
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/estudante_controller.rb
class EstudanteController < ApplicationController
  def index
    @estudantes = [
      { nome: "Maria", idade: 25, curso: "Engenharia Civil" },
      { nome: "Breno", idade: 31, curso: "Analise e Desenvolvimento de Sistemas" },
      { nome: "Andre", idade: 33, curso: "Matemática" }
    ]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @author = "Rodrigo"
      @posts = [
        { title: "Rails", body: "Aprendendo com a OBC" },
        { title: "Javascript", body: "Aprendendo com a OBC" },
        { title: "Python", body: "Aprendendo com a OBC" }
      ]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc) # Fazendo com que os comentários apareçam por ordem decrescente
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user  # Associando o usuário ao post

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :body ])
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>"
    style="border: 1px solid black; padding: 1em; margin: 1em;"
>
    <%= comment.user.email %> <br/>
    <% if (comment.updated_at - comment.created_at) > 1%>
        <span>Editado: <%= time_ago_in_words(comment.updated_at)%> atrás </span>
    <% else %>
        <span>Postado: <%= time_ago_in_words(comment.created_at) %> atrás</span>
    <% end %>
    <% if current_user == comment.user %>
        <div class="btn-group float-end">
            <%= link_to "Edit", nil, remote: true, class: "btn btn-warning",
            data: {
                controller: "comments",
                action: "comments#toggleForm",
                comments_form_param:"edit-form-#{comment.id}",
                comments_body_param:"comment-body-#{comment.id}"
            }%>
            <%= button_to "Delete", [post, comment], class:"btn btn-danger", method: :delete%>
        </div>
    <% end %>
    <div id="edit-form-<%=comment.id%>" class="d-none">
        <%= render "comments/form", 
            post: @post, 
            comment: comment,
            submit_label: "Update"
            
        %>
    </div>
    <hr/>
    <div id="comment-body-<%= comment.id %>" class="d-none">
        <%= comment.body %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment]) do |f| %>
    <div>
        <%= f.rich_text_area :body %>
        <%= f.submit submit_label, class: "btn btn-primary mt-1"  %>
    </div>
<% end %>

app/views/estudante/index.html.erb
<div class="container">
    <h2 style="text-align:center;">Informações dos Estudantes</h2>
    <hr>
    <% @estudantes.each do |estudante| %>
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= estudante[:nome] %>" aria-expanded="true" aria-controls="collapseOne">
                    <%= estudante[:nome] %>
                </button>
                </h2>
                <div id="collapse<%= estudante[:nome] %>" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <p><%= estudante[:idade] %> anos</p>
                    <p><%= estudante[:curso] %></p>
                </div>
                </div>
            </div>
        </div>
    <% end %>

    
    <%= link_to "Home", home_path %>
</div>

app/views/home/index.html.erb
<h1>Blog Pessoal</h1>
<p>Para conferir meus posts, clique no botão a seguir:</p>
<%= link_to "Blog", posts_path, class:"btn btn-primary" %>

app/views/layouts/_alerts.html.erb
<%if notice%>
    <p class="notice"><%= notice %></p>
<% elsif alert%>
    <p class="alert"><%= alert %></p>
<% end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <%= link_to "RailsBlog", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class:"nav-link"%>
        </li>
      </ul> 
      <ul class="navbar-nav">
        <%= render "user/session"%>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
      <%= render "layouts/alerts" %>
    </header>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: [post, comment]) do |f| %>
    <div class="form-control">
        <%= f.rich_text_area :body %>
        <%= f.submit submit_label, class: "btn btn-primary mt-1" %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
    <p>	<%= pluralize(post.views, "view") %> </p>
    <p>Publicado por: <%= post.user.email %></p>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

<%= render "comments/form", 
  post: @post, 
  comment: @post.comments.build,
  submit_label: "Reply"   
%>
<% @comments.each do |comment| %>
  <%= render "comments/comment", post: @post, comment: comment %>
<% end %>

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class:"d-flex") do |f|%>
    <%= f.search_field :title_or_body_cont,
        placeholder: "Search",
        class: "form-control me-2"
    %>
    <%= f.submit "Pesquisar", class: "btn btn-outline-success" %>
<% end %>

app/views/search/index.html.erb
<%= render "search/form" %>

app/views/user/_session.html.erb
<% if current_user%>

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Gerenciamento Usuário
        </a>
        <ul class="dropdown-menu dropdown-menu-lg-end">
        <li><%= link_to "Novo Post", new_post_path, class: "dropdown-item" %></li>
        <li><hr class="dropdown-divider"></li>
        <li>
            <%= link_to "Logout", destroy_user_session_path, data:{turbo_method: :delete}, class: "dropdown-item"%>
        </li>
        </ul>
    </li>

<% else %>
    <li class="nav-item">
        <%= link_to "Cadastro", new_user_registration_path, class: "nav-link"%>
    </li>

    <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link"%>
    </li>

<% end %>